### ISSUE TITLE
Test adding and updating ad-hoc variables with a project card

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#178]
Make sure the variable is set.

**Comment by jhelsel11** [comment]
@kulshresthaa, you can find the minimal project card here:
https://github.com/wsp-sag/client_met_council_network/blob/base_network_project_cards/data/interim/project_cards/error_in_reversible_managed%20lane.yml

I'm rerunning the network write out step with just that project card. Will update with results.

**Comment by kulshresthaa** [comment]
@jhelsel11 Two issues with the [project card](https://github.com/wsp-sag/client_met_council_network/commit/5f1dffef2b13dfc6e77f7e9ddaaaefdfa5b4892c): 
* project card category for roadway change is `Roadway Property Change` and you had `Roadway Attribute Change`. It wouldn't apply the project card because category isn't found. See [here](https://github.com/wsp-sag/network_wrangler/blob/develop/network_wrangler/roadwaynetwork.py#L1174) and [here](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/ProjectCard.py#L29)
I guess you are reading project card with `validate` as False, therefore it didn't complaint about missing category property, else your project card would have failed the validation. 

* The list of links under the link_id key for `facility` property isn't in the correct format. See below
![image](https://user-images.githubusercontent.com/13478750/82601650-bb527680-9b64-11ea-8c97-33c7d218506e.png)

Instead of `link` property being a dictionary, it should be a list of dictionary of different attributes to select/identify the project links

Meaning, instead of project card as 
```
changes:
- category: Roadway Attribute Change
  facility:
    link:
      model_link_id:
      - 382272
  properties:
```

it should be 
```
changes:
- category: Roadway Property Change
  facility:
    link:
      - model_link_id:
        - 382272
  properties:
```

See project card examples [1](https://github.com/wsp-sag/network_wrangler/blob/master/examples/stpaul/project_cards/1_simple_roadway_attribute_change.yml), [2](https://github.com/wsp-sag/network_wrangler/blob/master/examples/stpaul/project_cards/2_multiple_roadway.yml), [3](https://github.com/wsp-sag/network_wrangler/blob/master/examples/stpaul/project_cards/3_multiple_roadway_attribute_change.yml)

I've tested and once you fix the project card, it would be applied correctly. 

cc @e-lo @DavidOry
