### ISSUE TITLE
[FEATURE] more flexibility when selecting transit with the same changes

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#262]
### User Story
Currently wrangler can select multiple routes such as:
https://github.com/wsp-sag/network_wrangler/blob/fa101017117eccaa4885623a2f20fbad100aeec0/examples/stpaul/project_cards/8a_multi_transit_attribute_change.yml#L9-L14

It will be nice to allow individual route selections under `facility` (similar to [roadway](https://github.com/wsp-sag/network_wrangler/blob/fa101017117eccaa4885623a2f20fbad100aeec0/examples/stpaul/project_cards/3_multiple_roadway_attribute_change.yml#L9-L18)), which adds more freedom when selecting multiple transits.  This is the use case for MTC, e.g., a route correction for AM and EV:
```
- category: Transit Service Property Change
  facility:
    route:
    - route_id: '336'
      direction_id: 1
      start_time: 06:00
      end_time: '10:00'
    - route_id: '336'
      direction_id: 1
      start_time: '19:00'
      end_time: 03:00
  properties:
  - property: routing
    existing:
    - -1011411
    - -1018737
    - -1003258
    - -1003258
    - -1006801
    - 1019259
    - -1006801
    - -1019291
    - -1001466
    set:
    - -1011411
    - -1018737
    - 1019291
    - -1001466
```

### Priority 
high

### Level of Effort
low

### Resolution Ideas
see above

### Project
MTC major transit routing qa/qc

### Who should be involved?
Implementer: @i-am-sijia 
Commenters: @e-lo @DavidOry 
Reviewers: @e-lo @DavidOry 

### Risk
*Will this potentially break anything?*
unlikely

#### Tests
*What are relevant tests or what tests need to be created in order to determine that this issue is complete?*
see above

Need to update Lasso to write out this format.
