### ISSUE TITLE
[BUG] not removing loops in transit

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#263]
## Describe the bug
No errors returned, but the result is incorrect.  The loop still exists.

### Failing tests
MTC transit project cards, example see below:

```
project: SFMTA Route 336 Edits
tags:
  - 'Minor Transit'
dependencies: ''
changes:
- category: Transit Service Property Change
  facility:
    route_id: '336'
    direction_id: 0
  properties:
  - property: routing
    existing:
    - -1021778
    - 1000715
    - -1002699
    - -1007345
    - -1009452
    - 1000062
    - -1017085
    - -1017427
    - -1009452
    - -1007345
    set:
    - -1021778
    - 1000715
    - 1002699
    - -1007345
```

### Triggering line of code
https://github.com/wsp-sag/network_wrangler/blob/23de6c4ce4c7f0106c41993a4fcff3a76399796e/network_wrangler/transitnetwork.py#L867-L880

### Thoughts on resolution
List index() returns the index of the first occurrence of node `1007345`, to remove the loop, it should look for the last occurrence of `1007345`.

**Risk: would the fix break anything?**
