### ISSUE TITLE
[FEATURE] Default attribute values for new links/nodes

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#284]
### User Story
I am creating a new network link. There are attributes of my network, such as an observed count, that I do not want to enter in a Project Card. Rather, I'd like there to be a set of default values that are used for new links. This will make Project Cards for new links briefer and easier to manage.

### Priority 
Low

### Level of Effort
Low

### Resolution Ideas
Add default values for new link fields in `parameters.py`

### Project
None

### Who should be involved?
Implementer: @e-lo 
Commenters:  @DavidOry 
Users: @RachelWikenMC 
Reviewers: @i-am-sijia 

### Risk
Unlikely

#### Tests
Create a Project Card with an incomplete set of roadway attributes. Apply the Cards and check that the new link uses the default values.

**Comment by e-lo** [comment]
Wrangler operates on project cards and to date has been able to avoid any settings or parameterization outside of them.

Here are what I think are good implementation options for this use case: 

## 1a. Define "defaults" in individual Project Cards
Create "default" functionality within `Roadway Network Change` project card changes if a property doesn't exist yet.

```yaml
property: my_special_property
    default: 1. # sets the default value if property doesn't exist in network yet
    set: 2
```

The downside here is that there is less traceability and there is an order-of-applied dependency. For example, if you have a project card that you apply with a default of 1 first, that will be the default and a subsequent project card with a default of 2 would be ignored.  Option 1b offers a slight modification to this.

### Implementation
Fairly simple extension of current functions. 

## 1b. Define "else" values in individual Project Cards

```yaml
property: my_special_property
    else: 1. # sets the value for all unselected links
    set: 2
```
The downside here is that there is still a apply-order-dependency for project-card implementation order.  This is somewhat addressed in Option 1c. 

## 1b. Define "na" values in individual Project Cards

```yaml
property: my_special_property
    na: 1. # sets the value for all links that are currently NA/NaN
    set: 2
```

Here the main problem is still apply-order-dependency because if you apply a card with a na: 0 and then na: 1, it would use na: 0.   Furthermore, we have implemented "None" defaults of various types right now which would need to be changed....we wouldn't want to create a "update if none" option because None equivalents could be a purposeful value which was intentionally applied in an earlier project card. 

For this reason, I think Option 2 is the preferred option:

## 2. Define a "defaults" project card 

Since now you can select all in project card, you could define a "default value" project card at the outset which defined defaults for all links – which would then be updated by subsequent project cards.  This allows all the defaults to be checked in to a single project card which can be version-controlled and acts somewhat as a "config" of sorts.  If this proejct card is called first, then you can avoid the path-dependency in individual project cards. 

### Implementation
Doesn't require any changes to wrangler // update to docs.
