### ISSUE TITLE
Create example Managed Lane Project Card

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#30]
This will involve updating the design of the project card such that it can accurately describe the following details, without negating much of the consistency or simplicity associated with the simple change project card:
 1. Managed lane attachment method: 

For example:
  - separate facility with specific entry/exits to/from mainline 
  - separate lane with specific entry/exits to/from mainline 
  - separate lane with permeable boundary 

2. Managed lane characteristics: copied from mainline or new?
 - including any time of day considerations for access

3. Range of lane, including an option to break a link in middle if necessary.

------- moved to next sprint ----------
This initial managed lane project card will be highway only, with transit addressed in subsequent task.
 - What transit should move to managed lane? Move transit that should move.

**Comment by JonathanEhrlichMC** [comment]
Time of day considerations- for example this mainline has a managed lane which is open only in the AM peak, but is a GP lane all other times. Or this mainline has a managed shoulder which is open only in the AM peak but is closed (a shoulder) at other times, etc?

**Comment by e-lo** [comment]
Open street map restrictions by time of day: https://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Comment by kulshresthaa** [comment]
discussion about example managed lane project card in #68

**Comment by e-lo** [comment]
Per our stand up call today, the team agreed that this is the framework we will work with.

```yaml
properties:
  - property: LANES
    set: 3
    time_of_day:
      - time: ['7:00', '9:00']
        set: 2
      - time:  ['13:00', '16:00']
        set: 2
  - property: ML_LANES
    set: 0
    time_of_day:
      - time: ['7:00', '9:00']
        set: 1
      - time:  ['13:00', '16:00']
        set: 1
  - property: ML_PRICE
    set: 0
    group:
      - category: ['sov']
        time_of_day:
          - time: ['7:00', '9:00']
            set: 1.5
          - time: ['13:00', '16:00']
            set: 2.5
      - category: ['hov2']
        time_of_day:
          - time: ['7:00', '9:00']
            set: 1.0
          - time: ['13:00', '16:00']
            set: 2.0
  - property: ML_ACCESS
    set: 'all'
  - property: ML_EGRESS
    set: 'all'
```
