### ISSUE TITLE
Moving Transit Lines to Managed Lane

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#51]
Create a method in the TransitNetwork to move transit lines, as specified, to a parallel managed lane facility.

This may include querying which transit lines have stops that can be served if they are moved vs not.

**Comment by josiekre** [comment]
Can you provide an example project card? Mainly this is so that I can get my head around how this will come from Cube and therefore via the project card. 

See #61 for the latest example project card on transit.

**Comment by e-lo** [comment]
basically it should look like a managed lane project card...but
I added a new keyword: `actions`

Open to other ideas


```
project: test managed lane project with transit moving
category: Parallel Managed Lanes
tags:
   - 'example'
facility:
  link:
    - name:
      - 'I 35E'
  A:
    osmNodeId: '961117623'
  B:
    osmNodeId: '2564047368'
actions:
 - move_transit:
      - time: ['7:00', '9:00']
      - short_name: ...
properties:
  - property: LANES
    set: 3
    timeofday:
      - time: ['7:00', '9:00']
        set: 2
      - time: ['16:00', '19:00']
        set: 2
  - property: ML_LANES
    set: 0
    timeofday:
      - time: ['7:00', '9:00']
        set: 1
      - time: ['16:00', '19:00']
        set: 1
  - property: ML_PRICE
    set: 0
    group:
      - category: ['sov']
        timeofday:
          - time: ['7:00', '9:00']
            set: 1.5
          - time: ['16:00', '19:00']
            set: 2.5
      - category: ['hov2']
        timeofday:
          - time: ['7:00', '9:00']
            set: 1.0
          - time: ['16:00', '19:00']
            set: 2.0
  - property: ML_ACCESS
    set: 'all'
  - property: ML_EGRESS
    set: 'all'
notes: Placeholder for notes
```

**Comment by josiekre** [comment]
So many questions immediately come to mind...


Where does the graph information come from? How does TransitNetwork know what node IDs to move (existing, set)?

Why not have the project card use a "Transit Service Property Change" type to specify this instead? In the case project cards allow multiple types of changes in one card, Lasso would already have the node list and TransitNetwork could handle it like any other routing change.

**Comment by e-lo** [comment]
Well one of these is at least easier...

> Where does the graph information come from?

The link list, node list (route), and graph already exist from the selection query done in the roadway network. It can be accessed by using the following methods:

1. searches are stored by selection key, so create a selection key
https://github.com/wsp-sag/network_wrangler/blob/0f06a39b66d1f34d7a71f96113f7c1b1c952f178/network_wrangler/RoadwayNetwork.py#L454

2. https://github.com/wsp-sag/network_wrangler/blob/0f06a39b66d1f34d7a71f96113f7c1b1c952f178/network_wrangler/RoadwayNetwork.py#L628-L632

**Comment by e-lo** [comment]
> Why not have the project card use a "Transit Service Property Change" type to specify this instead? 

I think you mean route change?

> Lasso would already have the node list

I'm not sure how Lasso would already have the node list? Wrangler is treating each card individually in apply. In any case, we don't want to rely on Lasso for this functionality...it should be a core wrangler functionality.

**Comment by josiekre** [comment]
> I think you mean route change?

I put them into the same project card type. Is this a problem? Right now we only handle `headway_secs` and `routing` property changes so it seemed cleaner to use the existing functions rather than creating another project card type with a `routing` key instead of a `properties` key. 

```
project: Bus Reroute
category: Transit Service Property Change
tags:
   - existing_plus_committed
dependencies:
  prerequisites: []
  corequisites: []
  conflicts: []
facility:
  trip_id: 14944022-JUN19-MVS-BUS-Weekday-01
properties:
  - property: routing
    existing: [-1930, -1931, 1932]
    set: [-1930, 1931, 1932]
```
