### ISSUE TITLE
Create simple transit attribute change project card

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#55]
For now, let's start simple and make this a line-level change (i.e. headways) rather than addressing things like routing and stops.

In order to:
- test searching for transit lines
- manipulating transit network object
- write out manipulated transit network object

From the requirements document (this needs to be brought up to speed with current spec and will likely evolve):
```
Project: Blue Line Service Enhancement
Category: Transit Service Attribute Change
Tags: 
   - transit_vision
Dependencies:
   Prerequisite: None
   Corequisite: System-wide Bus Service Reduction
   Conflicts: None
Transit_Line: BLUE_LINE_MAIN 
Attribute: HEADWAY
Change:
   Time_Period: Morning Commute
      Existing: 10
	Build: 5
   Time_Period: Evening Commute
      Existing: 10
	Build: 5
Attribute: ROUTE_SEQUENCE
   Change: 
   Sequence: 5069, -5070, 5071, ...
Notes: Placeholder for notes
```

**Comment by e-lo** [comment]
**Approach for attribute changes**
```
LANES: 
	existing: 3
	set: 2

LANES:
	existing: 3
	change: -1
```

**Comment by josiekre** [comment]
Existing will be optional. Set *or* change is required (one or the other only).

**Comment by josiekre** [comment]
Closed w/ dae0153fbf927b6f6a46e943058acacda37dbb87. May require changes based on discussion in #71.

**Comment by e-lo** [comment]
I think to close this we need to figure out the specification for determining "what" you are changing to a headway of 900 seconds, right now (below) it is ambiguous. 

```
project: Blue Line Service Enhancement
changes:
  - type: Transit Service Attribute Change
    id: ...
    attributes:
      headway_secs:
        set: 900
```
