### ISSUE TITLE
Create a route-shape adjustment project card for Transit Line

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#60]
Create a project card that adjusts the following features:
- facilities the bus travels on
- the stopping pattern of the bus

Features should be adjusted based on querying routes that use a specific facility, i.e. buses that use a mainline freeway segment that are operated by a set of agencies.

**Comment by josiekre** [comment]
Example from PRD:

```
Project: Bus Reroute
Category: Transit Route Change
Tags: existing_plus_committed
Dependencies:
   Prerequisite: None
   Corequisite: None
   Conflicts: None
Facility:
“short_name”: “21”
Routing:
Replace:
Existing: [123,-234,345]
Set: [123,-232,233, 345]

Notes: A placeholder for notes
```
