### ISSUE TITLE
Extend transitNetwork search method to query by facility use

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#61]
Should be able to implement search as declared in  #60 
i.e. buses that use I-35 between A and B

Should also allow for multiple queries, i.e. I-35 between A and B or D and F; and then belonging to agency X.

**Comment by josiekre** [comment]
Can you provide more context for this issue? Perhaps an example project card? 

Here is what I have currently for any routing changes to a transit service.

```
project: Bus Reroute
category: Transit Service Property Change
tags:
   - existing_plus_committed
dependencies:
  prerequisites: []
  corequisites: []
  conflicts: []
facility:
  trip_id: 14944022-JUN19-MVS-BUS-Weekday-01
properties:
  - property: routing
    existing: [-1930, -1931, 1932]
    set: [-1930, 1931, 1932]
```

**Comment by e-lo** [comment]
Use case: getting a list of transit lines that are using a freeway facility between A and B from agency Z so that I can move them to the managed lane.

Project card: managed lane project card, i.e. 

```
facility:
  link:
    - name:
      - 'I 35E'
  A:
    osmNodeId: '961117623'
  B:
    osmNodeId: '2564047368'
```

Currently the RoadwayNetwork network search query will return the links that are involved; so you just need to cross-reference that with the shapes and any other selection criteria (i.e. time of day, etc)
