### ISSUE TITLE
Extend project card schema to be able to handle multiple changes

### ISSUE THREAD

**Issue by josiekre** [wsp-sag/network_wrangler#71]
In thinking about #55, I came up with an idea for the project card schema. I am copying a JSON-version with comments below and an equivalent YAML. I will draft the actual schema if there is consensus on the new approach.

I think the real change I am suggesting boils down to allowing more than one type of change per project card (Roadway Attribute Change, Transit Service Attribute Change). This will result in less overall project card files, a sensical approach to managed-lane project cards, and an easier-to-read summary of whatever the user thinks of the "project" as. I think we still keep `corequisites` as an option for flexibility in reusing cards of course.

I left a `...` for `id` because I need to think on that more. We want that element to be really flexible based on the type of change to allow one to specify either an identifier or a filter to search the network for features/service to apply the attribute change(s) to. Suggestions welcome.

```
{
  'project': '',  // required, string
  'notes': '',  // optional, string
  'tags': [],  // optional, array
  'dependencies': {  // optional, obj (keys must be one of prerequisite, corequisite, conflicts; values must be string that is not None b/c python brings YAML in as a string rather than null or python's None)
    'prerequisite': ''
  },
  'changes': [ // required, array of obj (each type of change should have its own schema and be incorporated with $ref
    {
      'type': 'Roadway Attribute Change',  // has to be in a set
      'id': ...,
      'attributes': {  // required, obj (keys can be anything, value must be an obj w/ either 'change' or 'set' being required and 'existing' optional)
        'LANES': {
          'change': -1,
          'existing': 3
        },
        'isTranLink': {
          'set': 1
        }
      }
    },
    {
      'type': 'Transit Service Attribute Change',
      'id': ...,
      'attributes': {
        'headway_secs': {
          'set': 900
        }
      }
    }
  ]
}
```

A bare minimum example:
```json
{
  "project": "Blue Line Service Enhancement",
  "changes": [
    {
      "type": "Transit Service Attribute Change",
      "id": ...,
      "attributes": {
        "headway_secs": {
          "set": 900
        }
      }
    },
    {
      "type": "Roadway Attribute Change",
      "id": ...,
      "attributes": {
        "LANES": {
          "change": -1
        }
      }
    }
  ]
}
```

Same example in YAML:
```yaml
project: Blue Line Service Enhancement
changes:
  - type: Transit Service Attribute Change
    id: ...
    attributes:
      headway_secs:
        set: 900
  - type: Roadway Attribute Change
    id: ...
    attributes:
      LANES:
        change: -1
```

What do you think? All comments welcome. (cc: @e-lo, @DavidOry, @kulshresthaa)

**Comment by e-lo** [comment]
Thanks for thinking this thru! My first reaction is that the ID field should actually be an....id of the change (i.e. `id: blue_line_service_increase`) and then we retain a similar structure to how the `facility` is coded in current projects cards, but with the added ability to do some querying based on attributes...  We could add some functions to the objects to make that easier.

**Comment by DavidOry** [comment]
I obviously hate the JSON, but like the idea of combining changes. Though I think we're starting to -- here and in other places -- over-engineer a bit. I'd like to get this into Rachel's hands as soon as we can and see if managing a lot of cards is burdensome for her. I like her to be driving this and other features.

**Comment by josiekre** [comment]
> I think we're starting to -- here and in other places -- over-engineer a bit.

What feels over-engineered? Let's address. 

- For some projects multiple changes are probably required (e.g. managed lane with bus rerouting, BRT with repetitive local bus, any project with link splitting for delete and add steps). 

- I think we could abandon the unique identifier for each change (`id`) in favor of the `facility` approach already developed for the first roadway attribute change. I think I was imagining the same thing but just called it `id` rather than `facility`. You okay with that @e-lo?

What else feels over-engineered @DavidOry?

**Comment by DavidOry** [comment]
Over-engineered was a poor word choice. Better to say that I'd like our reflex to be let's push our current approach out and see how the user responds. Right now we have the `Corequisite` field in the Project Card, which allows us to "connect" cards to a bigger idea. Let's see if that works.

**Comment by josiekre** [comment]
I'll see what I can do with it for transit...

Right now the project card schema has:

```
    "required": [
      "Project",
      "Category",
      "Tags",
      "Notes"
    ],
```

In addition, the optional top-level keys are: `Road`, `Attribute`, `Change`, `Dependencies`. I'll need to add something different than `Road` for transit. 

Although it looks like the latest example project cards in the repo are doing something like: `facility` (instead of `road`) and `properties` (instead of `attributes`). 🤷‍♀ The schema needs to get tighter. Which do we want? I'll fix up the schema to do better validation.

**Comment by josiekre** [comment]
@i-am-sijia Here is an updated example of a simple card:

```
project: Blue Line Service Enhancement
changes:
  - type: Transit Service Attribute Change
    facility:
      route_id: 21-111
      time: ['09:00', '15:00']
    properties:
      - property: headway_secs
        set: 900
  - type: Roadway Attribute Change
    facility:
      link:
        osmid: '223371529' # 6th St E
      A:
        osmNodeId: '187854529' # Jackson St
      B:
        osmNodeId: '187899923' # Robert St N
    properties:
      - property: LANES
        change: -1
```

For transit, you can use `trip_id`, `route_id`, `short_name`, or `long_name` to select transit service. You can optionally also specify a time if you want to be more specific in your selection. The `trip_id`, `route_id`, and `short_name` must match the GTFS data exactly to get a match. The `long_name` uses regular expressions to pull any text from the GTFS `route_long_name`. Project card 9 on the `simple_transit_project` branch shows this. 

Feel free to add more detail around managed lanes to the example @e-lo or @kulshresthaa. (cc: @DavidOry)
