### ISSUE TITLE
allow multiple changes per project card

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#94]
It should handle:

```
project:
tags:
prerequisites:...
changes:
   - category:
      selection:
      properties:
   - category:
      selection:
      properties:
notes:
```

I will implement this within the updated `apply` functionality.
